### ISSUE TITLE
chapter_1 代码问题

### ISSUE THREAD

**Issue by whyang78** [dongdonghy/Detection-PyTorch-Notebook#4]
在Evaluator.py文件中，函数GetPascalVOCMetrics()中对将dects按照置信度排序，代码有错误!  
原代码：  
dects = sorted(dects, key=lambda conf: conf[5], reverse=True)  
应该为： 
dects = sorted(dects, key=lambda conf: conf[4], reverse=True)

**Comment by dongdonghy** [comment]
> 在Evaluator.py文件中，函数GetPascalVOCMetrics()中对将dects按照置信度排序，代码有错误!
> 原代码：
> dects = sorted(dects, key=lambda conf: conf[5], reverse=True)
> 应该为：
> dects = sorted(dects, key=lambda conf: conf[4], reverse=True)

--------------------------
感谢指出，已修正。
